apiVersion: v1
kind: Pod
metadata:
  name: mongodb2
spec:
  volumes:
  - name: mongodb-data
    awsElasticBlockStore:
      volumeId: vol-05c8fb0d718a91dbf
      fsType: ext4
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
