apiVersion: v1
kind: Pod
metadata:
  name: mongodb1
spec:
  volumes:
  - name: mongodb-data
    awsElasticBlockStore:
      volumeId: vol-00ff66754e8ca426b
      fsType: ext4
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
      ports:
    - containerPort: 27017
      protocol: TCP
