apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv1
spec:
  capacity:
    storage: 60Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc-bla  # Optional (can be any name or omitted)
  csi:
    driver: ebs.csi.aws.com  # AWS EBS CSI driver name
    # volumeHandle: vol-1234567890abcdef0  # Replace with your EBS Volume ID vol-0fae22eb3984bec09
    volumeHandle: vol-0fae22eb3984bec09
    fsType: ext4  # Optional (defaults to ext4)
