apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc-bla  # Must match PV's storageClassName (if set)
  resources:
    requests:
      storage: 60Gi
