apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: od-test
  region: ap-southeast-1
  version: "1.30"

availabilityZones: ["ap-southeast-1a", "ap-southeast-1b"]

autoModeConfig:
  enabled: false

nodeGroups:
  - name: ng-od-1
    instanceType: t2.small
    desiredCapacity: 2

  - name: ng-od-2
    instanceType: t3a.small
    desiredCapacity: 1
