apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: abc-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/orvindemsy/argocd-example-apps.git
    targetRevision: master
    path: k8s/guestbook

    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    # server: https://7D4C557DA29DC913AA09821647F8310E.gr7.ap-southeast-1.eks.amazonaws.com
    namespace: abc-app

  syncPolicy:
    #automated:
    #  prune: true
    #  selfHeal: true
    #  allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

