apiVersion: v1
kind: Secret
metadata:
  namespace: argo
  name: argowf-helm-server-sa-token
  annotations:
    kubernetes.io/service-account.name: argo-workflows-server
type: kubernetes.io/service-account-token
